import React from 'react'

class ImpressionNotification extends React.Component {
  render() {
    return (
      <div className='ChannelList'>
        <h3 className='ChannelListTitle'>Impressions</h3>
        <p>Click on a user's image for a (very poor) impersonation of them!</p>
        <p>Generated by pseudo-random Markov Chains</p>
      </div>
    )
  }
}

export default ImpressionNotification
